#!/bin/bash

TAG="###dotfiles-lite###"

root=$([ -L "$0" ] && cd $(dirname $(readlink "$0")) || cd $(dirname "$0") &>/dev/null; pwd -P)

ln -fs "$root/zshrc" "$HOME/.zshrc"

if [[ ! -e "$HOME/.oh-my-zsh" ]]; then
  KEEP_ZSHRC=yes RUNZSH=no sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

mkdir -p "$HOME/.ssh"
ln -fs "$root/authorized_keys" "$HOME/.ssh/authorized_keys"

cron=$(crontab -l 2>/dev/null | sed "/$TAG/d")

[[ -n "$cron" ]] && cron+="\n"
cron+="00 09 * * * DISABLE_AUTO_UPDATE=true zsh -c 'source $HOME/.oh-my-zsh/oh-my-zsh.sh && omz update' &>/dev/null $TAG\n"
cron+="05 09 * * * '$root/update-git' $TAG"

echo -e "$cron" | crontab -
